### ISSUE TITLE
Synology 使用docker部署失败

### ISSUE THREAD

**Issue by DaDaDa12138** [gnehs/PokaPlayer#118]
![](https://raw.githubusercontent.com/DaDaDa12138/Uploader/master/img/20190103155525.png)

按照Wiki上的群辉docker搭建步骤后，docker启动十秒左右后报错，然后自动关机。

之后尝试在Mac 上使用node部署，npm start 之后依然报一样的错误。

![](https://raw.githubusercontent.com/DaDaDa12138/Uploader/master/img/20190103160032.png)

请问怎样可以解决这个问题呢？或者是否还需安装其他？

**Comment by gnehs** [comment]
config 文件可以發上來看看嗎

**Comment by DaDaDa12138** [comment]
![](https://raw.githubusercontent.com/DaDaDa12138/Uploader/master/img/20190103160956.png)

你好，config 文件指的是哪一个？

我刚看了下log文件，如下：
![image](https://user-images.githubusercontent.com/16765962/50668204-7da27d00-0f72-11e9-9fd2-452764009445.png)

**Comment by gnehs** [comment]
剛剛試過應該是程式碼上有錯誤，重新拉取新的 Docker image 應該就能解決
