### ISSUE TITLE
不會依照 Track Number 排序

### ISSUE THREAD

**Issue by adan89lion** [gnehs/PokaPlayer#129]
**Describe the bug 描述這個錯誤**
一般播放器會依照 Track Number 來排序音樂，但是 Poka 用 A-Z 排序，所以順序就不對。

**To Reproduce 如何重現**
1. Upload some music with ID3 tags (including track name, album name, genre, etc...) and also contains track number.
2. Open the album in PokaPlayer.
3. The album is sort by track name (A-Z) instead of track number (1-99).

**Expected behavior 預期會發生的行為**
A possibility to sort the album in a customisable way (track number, file name, genre, year, etc...).

**Screenshots 截圖**
I wish I could but I'm a freshman here.

**Desktop (please complete the following information):**
 - OS 作業系統: Chrome OS
 - Browser 瀏覽器 Google Chrome
 - Version 版本 Version 73.0.3683.48 (Official Build) beta (64-bit)

**Additional context 備註**
N/A

**Comment by gnehs** [comment]
已於 0.17.2 修正
