### ISSUE TITLE
Return to album list but at the previous location

### ISSUE THREAD

**Issue by adan89lion** [gnehs/PokaPlayer#166]
**Describe the bug 描述這個錯誤**
請描述這則 Bug。
I have about 100-200 albums, and when I tried to add multiple music from different albums to the play list, returning to the album list will make it to the top, not the previous location.

**To Reproduce 如何重現**
Steps to reproduce the behavior 重現的步驟:
1. Album list (and also artist list, folder etc...)
2. Tap album 69
3. Add songs in album 69
4. Return to the album list
5. Not at where album 69 is, but at the top of the page (album 1), so I have to scroll down so many times if I want to continue adding songs to playlist.

**Expected behavior 預期會發生的行為**
清楚描述您期望發生的事情。
Memorise the page location.

**Screenshots 截圖**
如果可以，請新增截圖以幫助解釋您的問題。
(none)

**Desktop (please complete the following information):**
 - OS 作業系統: Android P
 - Browser 瀏覽器 Chrome for Android
 - Version 版本 75

**Smartphone (please complete the following information):**
 - Device 裝置: ASUS ZenFone 5Z
 - OS 作業系統: Android P
 - Browser 瀏覽器 Google Chrome
 - Version 版本 75

**Additional context 備註**

**Comment by gnehs** [comment]
Fixed in [0.20.5](https://github.com/gnehs/PokaPlayer/releases/tag/0.20.5).
